package com.iDebug.pickloose.network;

public enum SERVICE {
    ADD_USER,
    GET_AUTH,
    DELETE_USER,
    MAKE_HOST,
    SET_GAME_SETTINGS,
    SET_READY,
    SET_NOT_READY,
    START_GAME,
    SET_TOOL,
    SET_COLOR,
    GET_CANVAS_SOCKET,
    CLEAR_CANVAS,
    GET_MEMBER,
    GET_ALL_MEMBER,
    VOTE_KICK,
    NEW_MESSAGE,
    GET_GAME_SETTINGS,
    ADD_REACTION,
    PLAY_MATCH,
    UPDATE_POINTS,
    UPDATE_TIMER,
    ROUND_RESULT
}
