package com.iDebug.pickloose.network;

public enum SERVICE {
    ADD_USER,
    GET_AUTH,
    DELETE_USER,
    MAKE_HOST,
    SET_GAME_SETTINGS,
    START_GAME,
    SELECT_TOOL,
    GET_CANVAS_SOCKET,
    UPDATE_CANVAS,
    GET_MEMBER,
    GET_ALL_MEMEBER,
    VOTE_KICK,
    NEW_MESSAGE,
    GET_GAME_SETTINGS, ADD_REACTION
}
